import "../styles/globals.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-stone-700 min-h-screen flex justify-start items-center flex-col gap-4 text-stone-300 p-4">
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
